# docker-compose.yml
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - traefik-certs:/letsencrypt
    networks:
      - traefik-network
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@local.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    networks:
      - traefik-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`pg-admin.gkibria121.com`)"
      - "traefik.http.routers.pgadmin.entrypoints=web"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dhaka
    volumes:
      - /mnt/storage/filebrowser/data/files:/srv
      - "/mnt/backup:/srv/PC Backup"
      - /mnt/storage/filebrowser.db:/database.db
      - /mnt/storage/filebrowser/filebrowser-config.json:/config.json

    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filebrowser.rule=Host(`filebrowser.gkibria121.com`)"
      - "traefik.http.routers.filebrowser.entrypoints=web"
      - "traefik.http.services.filebrowser.loadbalancer.server.port=80"
    networks:
      - traefik-network
  postgres:
    image: postgres:16
    restart: unless-stopped
    user: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
    volumes:
      - postgres-data-production:/var/lib/postgresql/data
    networks:
      - traefik-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USERNAME:-laravel} -d ${POSTGRES_DATABASE:-app}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest 
    volumes:
      - ~/.audiobooks/config:/config
      - ~/.audiobooks/metadata:/metadata
      - /mnt/backup/courses/Audiobooks:/audiobooks
      - /mnt/backup/courses/podcasts:/podcasts
    environment:
      - TZ=America/Toronto
    restart: unless-stopped 
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.audiobookshelf.rule=Host(`audiobookshelf.gkibria121.com`)"
      - "traefik.http.routers.audiobookshelf.entrypoints=web"
      - "traefik.http.services.audiobookshelf.loadbalancer.server.port=80"
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dhaka
      - WEBUI_PORT=8080
      - TORRENTING_PORT=21439
    volumes:
      - ~/.config:/config
      - /mnt/backup/courses/Audiobooks:/downloads   # change to your actual downloads path
    ports:
      - "21439:21439"        # torrent traffic - TCP
      - "21439:21439/udp"    # torrent traffic - UDP
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.gkibria121.com`)"
      - "traefik.http.routers.qbittorrent.entrypoints=web"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080" 
  koodo-reader:
    image: ghcr.io/koodo-reader/koodo-reader:master
    container_name: koodo-reader
    restart: unless-stopped
    environment:
      ENABLE_HTTP_SERVER: "true"          # enables data source feature
      SERVER_USERNAME: "gkibria"            # change this
      SERVER_PASSWORD: "gkibria121"      # change this
      ENABLE_OPDS: "true"                  # set false if you don't need OPDS
      ENABLE_KOREADER_SERVER: "true"       # set false if you don't need KOReader sync
      ENABLE_KOREADER_REGISTRATION: "false"
      ALLOWED_ORIGINS: "http://koodo-reader.gkibria121.com" 
    volumes:
      - /mnt/backup/courses/Audiobooks:/app/uploads     # web UI (only needed if not routing through Traefik)  
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.koodo-reader.rule=Host(`koodo-reader.gkibria121.com`)"
      - "traefik.http.routers.koodo-reader.entrypoints=web"
      - "traefik.http.services.koodo-reader.loadbalancer.server.port=80" 


volumes:
  
  pgadmin-data:
  postgres-data-production:
  sp_data:
  traefik-certs:
networks:
  traefik-network:
    external: true
