api:
  dashboard: true

log:
  level: INFO 
  
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  db:
    address: ":5432"  # TCP port
providers:
  file:
    filename: /etc/traefik/dynamic.yml
